apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: es-config
data:
  discovery.type: "single-node"
  ELASTICSEARCH_HOSTS: "http://subject-4-elastic-search:9200"

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: subject-4-elastic-search
  name: subject-4-elastic-search
spec:
  containers:
  - image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    name: subject-4-elastic-search
    env:
    - name: discovery.type
      valueFrom:
        configMapKeyRef:
          name: es-config
          key: discovery.type
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: subject-4-elastic-search
  name: subject-4-elastic-search
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    run: subject-4-elastic-search
status:
  loadBalancer: {}
