apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: subject-4-logging-sidecar
  name: subject-4-logging-sidecar
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: log-volumnes
      mountPath: /var/log/nginx
     
  - image: docker.elastic.co/beats/filebeat:7.14.1
    name: filebeat-sidecar
    env:
    - name: ELASTICSEARCH_HOSTS
      valueFrom:
        configMapKeyRef:
          name: es-config
          key: ELASTICSEARCH_HOSTS
    volumeMounts:
    - name: log-volumnes
      mountPath: /var/log/nginx
    - name: filebeat-nginx-module
      mountPath: /usr/share/filebeat/modules.d
  
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
  - name: log-volumnes
    emptyDir: {}
  - name: filebeat-nginx-module
    configMap:
      name: filebeat-nginx-module
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: subject-4-logging-sidecar
  name: subject-4-logging-sidecar
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: subject-4-logging-sidecar
status:
  loadBalancer: {}

---

apiVersion: v1
data:
  nginx.yml: |

    - module: nginx
      access:
        enabled: true
        var.paths: ["/var/log/nginx/access.log*"]

      error:
        enabled: true
        var.paths: ["/var/log/nginx/error.log*"]
      
      ingress_controller:
        enabled: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: filebeat-nginx-module
